version: '1.9'
services:
  client:
    container_name: client
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - app
    networks:
      - app-network
  app:
    container_name: app
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3500:3500"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
