version: '1.9'
services:
  client: 
    container_name: client
    restart: always
    build: ./front
    ports: 
      - "5174:5174"
    links: 
      - app
  app:
    container_name: app
    restart: always
    build: ./back
    ports: 
      - "3500:3500"
